################################################################################
#An example for tranforming a plink.mdist distance matrix to a list format
#
#@author:charles.hefer@codomics.com
################################################################################
GIT_REPO:https://github.com/codomics/blog.git

all:
	
################################################################################
#GIT PULL requests
################################################################################
plink.mdist:
	git pull 
